source.. = src/
bin.includes = plugin.xml,\
               about.ini,\
               plugin.properties,\
               META-INF/,\
               .,\
               icons/,\
               schema/,\
               epl-2.0.html
jars.compile.order = .
src.includes = icons/,\
               schema/,\
               epl-2.0.html
